# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

env = GDK_SCALE,2
monitor = , preferred, auto, auto
# monitor = eDP-1, 2880x1800@120, 0x540, 2
# monitor = DP-10, 2560x1440@59.95, 1440x0, 1
# monitor = DP-8, 2560x1440@59.95, 4000x0, 1

workspace = 1, monitor:eDP-1
workspace = 2, monitor:DP-10
workspace = 3, monitor:DP-8

workspace = 4, monitor:DP-10
workspace = 5, monitor:DP-10
workspace = 6, monitor:DP-10
workspace = 7, monitor:DP-10
workspace = 8, monitor:DP-10
workspace = 9, monitor:DP-10
